/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GameLevelService } from "../gameLevel.service";
import { GameLevelCreateInput } from "./GameLevelCreateInput";
import { GameLevel } from "./GameLevel";
import { GameLevelFindManyArgs } from "./GameLevelFindManyArgs";
import { GameLevelWhereUniqueInput } from "./GameLevelWhereUniqueInput";
import { GameLevelUpdateInput } from "./GameLevelUpdateInput";
import { QuestionFindManyArgs } from "../../question/base/QuestionFindManyArgs";
import { Question } from "../../question/base/Question";
import { QuestionWhereUniqueInput } from "../../question/base/QuestionWhereUniqueInput";

export class GameLevelControllerBase {
  constructor(protected readonly service: GameLevelService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: GameLevel })
  async createGameLevel(
    @common.Body() data: GameLevelCreateInput
  ): Promise<GameLevel> {
    return await this.service.createGameLevel({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [GameLevel] })
  @ApiNestedQuery(GameLevelFindManyArgs)
  async gameLevels(@common.Req() request: Request): Promise<GameLevel[]> {
    const args = plainToClass(GameLevelFindManyArgs, request.query);
    return this.service.gameLevels({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: GameLevel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async gameLevel(
    @common.Param() params: GameLevelWhereUniqueInput
  ): Promise<GameLevel | null> {
    const result = await this.service.gameLevel({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: GameLevel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateGameLevel(
    @common.Param() params: GameLevelWhereUniqueInput,
    @common.Body() data: GameLevelUpdateInput
  ): Promise<GameLevel | null> {
    try {
      return await this.service.updateGameLevel({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: GameLevel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteGameLevel(
    @common.Param() params: GameLevelWhereUniqueInput
  ): Promise<GameLevel | null> {
    try {
      return await this.service.deleteGameLevel({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/questions")
  @ApiNestedQuery(QuestionFindManyArgs)
  async findQuestions(
    @common.Req() request: Request,
    @common.Param() params: GameLevelWhereUniqueInput
  ): Promise<Question[]> {
    const query = plainToClass(QuestionFindManyArgs, request.query);
    const results = await this.service.findQuestions(params.id, {
      ...query,
      select: {
        content: true,
        createdAt: true,

        gameLevel: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/questions")
  async connectQuestions(
    @common.Param() params: GameLevelWhereUniqueInput,
    @common.Body() body: QuestionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      questions: {
        connect: body,
      },
    };
    await this.service.updateGameLevel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/questions")
  async updateQuestions(
    @common.Param() params: GameLevelWhereUniqueInput,
    @common.Body() body: QuestionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      questions: {
        set: body,
      },
    };
    await this.service.updateGameLevel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/questions")
  async disconnectQuestions(
    @common.Param() params: GameLevelWhereUniqueInput,
    @common.Body() body: QuestionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      questions: {
        disconnect: body,
      },
    };
    await this.service.updateGameLevel({
      where: params,
      data,
      select: { id: true },
    });
  }
}
